### ISSUE TITLE
How would a code stub look like to send data to ditto?

### ISSUE THREAD

**Issue by JulianFeinauer** [JulianFeinauer/ditto-mqtt#3]
Do I have to assemble that on my own or are there helper methods to do that for me?

**Comment by kolotu** [comment]
For the sending you would need to use the Ditto APIs or maybe even their client. For the data structure you can use the Eclipse Ditto generator (JsonSchema option). It will generate the proper format for your data.

**Comment by kolotu** [comment]
https://vorto.eclipse.org/api/v1/generators/eclipseditto/models/org.apache.plc4x.examples:SimulatedPlcTwo:1.0.0/?target=jsonSchema

**Comment by kolotu** [comment]
But I think for this example implementation that might be a bit overkill. Assembling manually would be easier for this use case.
